### PR TITLE
Initial changes to the Formly-Foundation template repo. Removed bootstrap styles, formatting and markup that was not needed.

### PR DESCRIPTION
**Pull request by httpJunkie**
Made minimal code JavaScript changes or fundamental syntax or naming convention changes. Most of the work done here was creating types and wrappers that would not spit out classes but instead make sure that the forms being outputted were plain html forms which is what Foundation uses.

### CODE REVIEW

**Comment by kentcdodds** [comment]
This is super awesome @httpJunkie. Thanks for working on it! Do you feel like it's ready to be released and announced?

**Comment by httpJunkie** [comment]
Heh, I would like to be able to either go over it with you or one of the
other team members. I have concerns about needing a template period for
Foundation (Aside from the more complex things like button groups and
advanced formy things) But what I have done here is make sure it works with
some simple examples and so far it does.

I have a few more commits to make.... But if there is anyone who may have
30 mins or so I would like to gt a code review and have them maybe even
test it out. Suggest changes if needed. Remember I am very green in this
area.

One more thing I was noticing and I fixed in some cases but not in others.

There were naming conventions like BootstrapHasError and BootstrapLabel,
conventions of that nature that seem like they do the same thing in one
template repo to the next. Giving these items names like templateHasError
and templateLabel and should probably be named like this throughout the
different repos for consistency. There are other instances of this type of
naming convention that although doesn't affect anything functionally, it
bugs me. THose are a few of the things I would like to get an opinion on
too.

OVERALL, I want to do more and be a part of this. I think there are some
minor changes and some basic testing that should be done before we push it
out to the public officially, but yeah were close I THINK. But again, I'm
green and I have concerns that someone with more knowledge of the big
picture may be able to help with.

On Fri, May 29, 2015 at 11:49 AM, Kent C. Dodds notifications@github.com
wrote:

> This is super awesome @httpJunkie https://github.com/httpJunkie. Thanks
> for working on it! Do you feel like it's ready to be released and announced?
> 
> ## 
> 
> Reply to this email directly or view it on GitHub
> https://github.com/formly-js/angular-formly-templates-foundation/pull/3#issuecomment-106854041
> .

## 

Respectfully,
Eric Bishard
Orlando, FL
(321) 208-0997 Cell
www.httpJunkie.com http://www.orangeappraisal.com/

**Comment by kentcdodds** [comment]
I did review your changes and I think they're good. Especially if it's working. I think if we get something out there that's working with a few examples, then people will start using it and we'll be able to get some feedback and make improvements to the implementation.

As for the naming conventions, I actually like to be explicit about the framework we're using, because the templates are quite different from one another, it ensures that people know what they're doing when they use those wrappers.

Let me know when you want to do a release, and I'll get it out there. Feel free to create an example or two for the website :-)

**Comment by httpJunkie** [comment]
HI Kent, sorry, I have been looking for a new job this week and
interviewing as well as my other job. I think you are right. Let's do what
we gotta do. If you think it's ok to go, let's do it!

I'm done with my interviews for the week so let me know what the next step
should be and I'll help get it done.

On Fri, May 29, 2015 at 10:25 PM, Kent C. Dodds notifications@github.com
wrote:

> I did review your changes and I think they're good. Especially if it's
> working. I think if we get something out there that's working with a few
> examples, then people will start using it and we'll be able to get some
> feedback and make improvements to the implementation.
> 
> As for the naming conventions, I actually like to be explicit about the
> framework we're using, because the templates are quite different from one
> another, it ensures that people know what they're doing when they use those
> wrappers.
> 
> Let me know when you want to do a release, and I'll get it out there. Feel
> free to create an example or two for the website :-)
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/formly-js/angular-formly-templates-foundation/pull/3#issuecomment-106976417
> .

## 

Respectfully,
Eric Bishard
Orlando, FL
(321) 208-0997 Cell
www.httpJunkie.com http://www.orangeappraisal.com/

**Comment by kentcdodds** [comment]
Did you see the issue on the repo? Someone's trying to use it (already!
Woot!) and they're having some trouble. If you could address that first,
that would be good :-)

-Kent C. Dodds

**Comment by kentcdodds** [comment]
Also, if you could make a few examples
https://www.youtube.com/watch?v=4dsXXTPET4A&list=PLV5CVI1eNcJi7lVVIuNyRhEuck1Z007BH&index=3
for the website that would be a good quick sanity test to make sure that it
actually works and show people how to use it.

-Kent C. Dodds

**Pull request merged**
